//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExprodesC.Lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExprodesC.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string cap_add {
            get {
                return ResourceManager.GetString("cap_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a genotype.
        /// </summary>
        public static string cap_add_genotype {
            get {
                return ResourceManager.GetString("cap_add_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a synonym.
        /// </summary>
        public static string cap_add_synonym {
            get {
                return ResourceManager.GetString("cap_add_synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base population.
        /// </summary>
        public static string cap_base_population {
            get {
                return ResourceManager.GetString("cap_base_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При создании популяции на основе другой, для новой популяции создаются новые локусы и аллели. Данные по локусам и аллелям, в том числе имена и частоты встречаемости - копируются..
        /// </summary>
        public static string cap_base_population_desc {
            get {
                return ResourceManager.GetString("cap_base_population_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A population is based on a population.
        /// </summary>
        public static string cap_based_population {
            get {
                return ResourceManager.GetString("cap_based_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculations.
        /// </summary>
        public static string cap_calculate {
            get {
                return ResourceManager.GetString("cap_calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string cap_close {
            get {
                return ResourceManager.GetString("cap_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comparison of genotypes.
        /// </summary>
        public static string cap_compare {
            get {
                return ResourceManager.GetString("cap_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Experts/Controls.
        /// </summary>
        public static string cap_contols {
            get {
                return ResourceManager.GetString("cap_contols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string cap_del {
            get {
                return ResourceManager.GetString("cap_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Down.
        /// </summary>
        public static string cap_down {
            get {
                return ResourceManager.GetString("cap_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download population.
        /// </summary>
        public static string cap_down_population {
            get {
                return ResourceManager.GetString("cap_down_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string cap_edit {
            get {
                return ResourceManager.GetString("cap_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing the allele.
        /// </summary>
        public static string cap_edit_allele {
            get {
                return ResourceManager.GetString("cap_edit_allele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing the genotype.
        /// </summary>
        public static string cap_edit_genotype {
            get {
                return ResourceManager.GetString("cap_edit_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing the locus.
        /// </summary>
        public static string cap_edit_locus {
            get {
                return ResourceManager.GetString("cap_edit_locus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing the population.
        /// </summary>
        public static string cap_edit_population {
            get {
                return ResourceManager.GetString("cap_edit_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing the synonym.
        /// </summary>
        public static string cap_edit_synonym {
            get {
                return ResourceManager.GetString("cap_edit_synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as....
        /// </summary>
        public static string cap_file_save_as {
            get {
                return ResourceManager.GetString("cap_file_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequency of occurrence of the allele.
        /// </summary>
        public static string cap_freq_allele {
            get {
                return ResourceManager.GetString("cap_freq_allele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From file.
        /// </summary>
        public static string cap_from_file {
            get {
                return ResourceManager.GetString("cap_from_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Genotypes.
        /// </summary>
        public static string cap_genotypes {
            get {
                return ResourceManager.GetString("cap_genotypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of genotypes.
        /// </summary>
        public static string cap_genotypes_list {
            get {
                return ResourceManager.GetString("cap_genotypes_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string cap_help {
            get {
                return ResourceManager.GetString("cap_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide genotypes.
        /// </summary>
        public static string cap_hide_genotypes {
            get {
                return ResourceManager.GetString("cap_hide_genotypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is calculated.
        /// </summary>
        public static string cap_is_calculate {
            get {
                return ResourceManager.GetString("cap_is_calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Library.
        /// </summary>
        public static string cap_library {
            get {
                return ResourceManager.GetString("cap_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Locuses.
        /// </summary>
        public static string cap_locuses {
            get {
                return ResourceManager.GetString("cap_locuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min. frequency.
        /// </summary>
        public static string cap_min_freq {
            get {
                return ResourceManager.GetString("cap_min_freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequency of mutation.
        /// </summary>
        public static string cap_mut_freq {
            get {
                return ResourceManager.GetString("cap_mut_freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string cap_name {
            get {
                return ResourceManager.GetString("cap_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of allele.
        /// </summary>
        public static string cap_name_allele {
            get {
                return ResourceManager.GetString("cap_name_allele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of locus.
        /// </summary>
        public static string cap_name_locus {
            get {
                return ResourceManager.GetString("cap_name_locus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of population.
        /// </summary>
        public static string cap_name_population {
            get {
                return ResourceManager.GetString("cap_name_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New allele.
        /// </summary>
        public static string cap_new_allele {
            get {
                return ResourceManager.GetString("cap_new_allele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New locus.
        /// </summary>
        public static string cap_new_locus {
            get {
                return ResourceManager.GetString("cap_new_locus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New population.
        /// </summary>
        public static string cap_new_population {
            get {
                return ResourceManager.GetString("cap_new_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New synonym.
        /// </summary>
        public static string cap_new_synonym {
            get {
                return ResourceManager.GetString("cap_new_synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string cap_off {
            get {
                return ResourceManager.GetString("cap_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On.
        /// </summary>
        public static string cap_on {
            get {
                return ResourceManager.GetString("cap_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string cap_open {
            get {
                return ResourceManager.GetString("cap_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profiles.
        /// </summary>
        public static string cap_profiles {
            get {
                return ResourceManager.GetString("cap_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project.
        /// </summary>
        public static string cap_project {
            get {
                return ResourceManager.GetString("cap_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a project or a file with genotypes.
        /// </summary>
        public static string cap_project_files_select {
            get {
                return ResourceManager.GetString("cap_project_files_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load.
        /// </summary>
        public static string cap_project_load {
            get {
                return ResourceManager.GetString("cap_project_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New project.
        /// </summary>
        public static string cap_project_new {
            get {
                return ResourceManager.GetString("cap_project_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project Selection.
        /// </summary>
        public static string cap_projects_select {
            get {
                return ResourceManager.GetString("cap_projects_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string cap_save {
            get {
                return ResourceManager.GetString("cap_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string cap_select {
            get {
                return ResourceManager.GetString("cap_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string cap_setting {
            get {
                return ResourceManager.GetString("cap_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show genotypes.
        /// </summary>
        public static string cap_show_genotypes {
            get {
                return ResourceManager.GetString("cap_show_genotypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synonyms.
        /// </summary>
        public static string cap_synonyms {
            get {
                return ResourceManager.GetString("cap_synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string cap_unselect {
            get {
                return ResourceManager.GetString("cap_unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Up.
        /// </summary>
        public static string cap_up {
            get {
                return ResourceManager.GetString("cap_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload population.
        /// </summary>
        public static string cap_up_population {
            get {
                return ResourceManager.GetString("cap_up_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload to Excel.
        /// </summary>
        public static string cap_upload_to_excel {
            get {
                return ResourceManager.GetString("cap_upload_to_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation of deletion.
        /// </summary>
        public static string conf_delete {
            get {
                return ResourceManager.GetString("conf_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm the deletion of the allele&apos;{0}&apos;.
        /// </summary>
        public static string conf_delete_allele {
            get {
                return ResourceManager.GetString("conf_delete_allele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm the deletion of the genotype &apos;{0}&apos;.
        /// </summary>
        public static string conf_delete_genotype {
            get {
                return ResourceManager.GetString("conf_delete_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm the deletion of the locus&apos;{0}&apos;.
        /// </summary>
        public static string conf_delete_locus {
            get {
                return ResourceManager.GetString("conf_delete_locus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm the deletion of the population &apos;{0}&apos;.
        /// </summary>
        public static string conf_delete_population {
            get {
                return ResourceManager.GetString("conf_delete_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm the deletion of the synonym &apos;{0}&apos;.
        /// </summary>
        public static string conf_delete_synonym {
            get {
                return ResourceManager.GetString("conf_delete_synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If not selected, the allele will be deleted without notifying the user..
        /// </summary>
        public static string desc_confirm_delete_allele {
            get {
                return ResourceManager.GetString("desc_confirm_delete_allele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If not selected, the genotype will be deleted without notifying the user..
        /// </summary>
        public static string desc_confirm_delete_genotype {
            get {
                return ResourceManager.GetString("desc_confirm_delete_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If not selected, the locus will be deleted without notifying the user..
        /// </summary>
        public static string desc_confirm_delete_locus {
            get {
                return ResourceManager.GetString("desc_confirm_delete_locus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If not selected, the population will be deleted without notifying the user..
        /// </summary>
        public static string desc_confirm_delete_population {
            get {
                return ResourceManager.GetString("desc_confirm_delete_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если пункт «Участвует в расчетах» не отмечен, то данный локус в математических расчетах не учитывается, но его профиль выводится в таблицу генотипов .
        /// </summary>
        public static string desc_is_calc {
            get {
                return ResourceManager.GetString("desc_is_calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The control/expert &apos;{0}&apos; has not been added to the list.
        /// </summary>
        public static string err_add_expert {
            get {
                return ResourceManager.GetString("err_add_expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error adding locus.
        /// </summary>
        public static string err_add_locus {
            get {
                return ResourceManager.GetString("err_add_locus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when creating a population.
        /// </summary>
        public static string err_add_population {
            get {
                return ResourceManager.GetString("err_add_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when creating a synonyn.
        /// </summary>
        public static string err_add_synonym {
            get {
                return ResourceManager.GetString("err_add_synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when editing the population.
        /// </summary>
        public static string err_edit_population {
            get {
                return ResourceManager.GetString("err_edit_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File upload error.
        /// </summary>
        public static string err_load_profile {
            get {
                return ResourceManager.GetString("err_load_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The population name must be unique..
        /// </summary>
        public static string err_pop_unique {
            get {
                return ResourceManager.GetString("err_pop_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculation error.
        /// </summary>
        public static string err_research_calc {
            get {
                return ResourceManager.GetString("err_research_calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The synonym name must be unique..
        /// </summary>
        public static string err_synonym_unique {
            get {
                return ResourceManager.GetString("err_synonym_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (by default).
        /// </summary>
        public static string msg_by_default {
            get {
                return ResourceManager.GetString("msg_by_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The current population cannot be deleted or edited. You need to select a different population, the default population, and then delete or edit the current one..
        /// </summary>
        public static string msg_cant_delete_population {
            get {
                return ResourceManager.GetString("msg_cant_delete_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Genotype is not selected.
        /// </summary>
        public static string msg_genotype_not_selected {
            get {
                return ResourceManager.GetString("msg_genotype_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Never show me this again.
        /// </summary>
        public static string msg_no_show {
            get {
                return ResourceManager.GetString("msg_no_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The &apos;{0}&apos; was saved successfully on the way &apos;{1}&apos;.
        /// </summary>
        public static string msg_object_saved {
            get {
                return ResourceManager.GetString("msg_object_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        public static string msg_page_appearance {
            get {
                return ResourceManager.GetString("msg_page_appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculations.
        /// </summary>
        public static string msg_page_calc {
            get {
                return ResourceManager.GetString("msg_page_calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the flag is set, then when trying to delete a synonym, a window appears asking for confirmation to delete the allele.
        /// </summary>
        public static string msg_page_conf_delete_allele {
            get {
                return ResourceManager.GetString("msg_page_conf_delete_allele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the flag is set, then when trying to delete a synonym, a window appears asking for confirmation to delete the genotype.
        /// </summary>
        public static string msg_page_conf_delete_genotype {
            get {
                return ResourceManager.GetString("msg_page_conf_delete_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the flag is set, then when trying to delete a synonym, a window appears asking for confirmation to delete the locus.
        /// </summary>
        public static string msg_page_conf_delete_locus {
            get {
                return ResourceManager.GetString("msg_page_conf_delete_locus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the flag is set, then when trying to delete a synonym, a window appears asking for confirmation to delete the population..
        /// </summary>
        public static string msg_page_conf_delete_population {
            get {
                return ResourceManager.GetString("msg_page_conf_delete_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the flag is set, then when trying to delete a synonym, a window appears asking for confirmation to delete the synonym..
        /// </summary>
        public static string msg_page_conf_delete_synonym {
            get {
                return ResourceManager.GetString("msg_page_conf_delete_synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmations.
        /// </summary>
        public static string msg_page_confirmations {
            get {
                return ResourceManager.GetString("msg_page_confirmations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Templates.
        /// </summary>
        public static string msg_page_templates {
            get {
                return ResourceManager.GetString("msg_page_templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploading a file.
        /// </summary>
        public static string msg_uploading_file {
            get {
                return ResourceManager.GetString("msg_uploading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Methods of calculation.
        /// </summary>
        public static string set_blend_methods_name {
            get {
                return ResourceManager.GetString("set_blend_methods_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на calc_decimal_places,The number of decimal places displayed.
        /// </summary>
        public static string set_decimal_number {
            get {
                return ResourceManager.GetString("set_decimal_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows exactly up to which character the final result will be displayed..
        /// </summary>
        public static string set_decimal_number_desc {
            get {
                return ResourceManager.GetString("set_decimal_number_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Defines the display of calculation results, in exponential or decimal form.
        /// </summary>
        public static string set_disp_values_desk {
            get {
                return ResourceManager.GetString("set_disp_values_desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Displaying values.
        /// </summary>
        public static string set_displaying_values {
            get {
                return ResourceManager.GetString("set_displaying_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The values of mutation frequencies of locuses for which data are not available are calculated by this method from the available (entered) actual frequencies,,.
        /// </summary>
        public static string set_method_calc_desc {
            get {
                return ResourceManager.GetString("set_method_calc_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum number of mutations.
        /// </summary>
        public static string set_number_mutation {
            get {
                return ResourceManager.GetString("set_number_mutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of mismatched alleles in the genotype, at different loci, after which the genotype will be considered different from the original.
        /// </summary>
        public static string set_number_mutation_desc {
            get {
                return ResourceManager.GetString("set_number_mutation_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Priority Pmin.
        /// </summary>
        public static string set_priority {
            get {
                return ResourceManager.GetString("set_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It is used to indicate the priorities of the frequencies used if the library of loci contains alleles with frequencies lower than the specified Pmin for a particular locus. When the Pmin point is marked, the frequency of the Pmin locus will be used in calculations if the frequency of the allele used is less than the frequency of the Pmin..
        /// </summary>
        public static string set_priority_desc {
            get {
                return ResourceManager.GetString("set_priority_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application Theme.
        /// </summary>
        public static string set_theme {
            get {
                return ResourceManager.GetString("set_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select your preferred application theme from the list..
        /// </summary>
        public static string set_theme_desc {
            get {
                return ResourceManager.GetString("set_theme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequency profile used.
        /// </summary>
        public static string set_used_population {
            get {
                return ResourceManager.GetString("set_used_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string theme_dark {
            get {
                return ResourceManager.GetString("theme_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string theme_light {
            get {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System theme.
        /// </summary>
        public static string theme_sys {
            get {
                return ResourceManager.GetString("theme_sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The default template.
        /// </summary>
        public static string tpl_empty_template {
            get {
                return ResourceManager.GetString("tpl_empty_template", resourceCulture);
            }
        }
    }
}
