//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExprodesC.Lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExprodesC.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Likelihood ratio.
        /// </summary>
        public static string calc_method_lr {
            get {
                return ResourceManager.GetString("calc_method_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of a random match.
        /// </summary>
        public static string calc_method_p {
            get {
                return ResourceManager.GetString("calc_method_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probability of identity/kinship.
        /// </summary>
        public static string calc_method_pp {
            get {
                return ResourceManager.GetString("calc_method_pp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A mixture of 2 persons (2 assumed persons).
        /// </summary>
        public static string calc_mix_aa {
            get {
                return ResourceManager.GetString("calc_mix_aa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A mixture of 3 persons (3 assumed persons).
        /// </summary>
        public static string calc_mix_aaa {
            get {
                return ResourceManager.GetString("calc_mix_aaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A mixture of 3 persons (2 suspected + 1 unknown).
        /// </summary>
        public static string calc_mix_aau {
            get {
                return ResourceManager.GetString("calc_mix_aau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A mixture of 2 persons (1 assumed + 1 unknown).
        /// </summary>
        public static string calc_mix_au {
            get {
                return ResourceManager.GetString("calc_mix_au", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A mixture of 3 persons (1 presumed + 2 unknown).
        /// </summary>
        public static string calc_mix_auu {
            get {
                return ResourceManager.GetString("calc_mix_auu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Direct identification.
        /// </summary>
        public static string calc_mix_direct {
            get {
                return ResourceManager.GetString("calc_mix_direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A mixture of 2 persons (1 known + 1 assumed).
        /// </summary>
        public static string calc_mix_ka {
            get {
                return ResourceManager.GetString("calc_mix_ka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A mixture of 3 persons (1 known + 2 suspected).
        /// </summary>
        public static string calc_mix_kaa {
            get {
                return ResourceManager.GetString("calc_mix_kaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A mixture of 3 persons (1 known + 1 assumed + 1 unknown).
        /// </summary>
        public static string calc_mix_kau {
            get {
                return ResourceManager.GetString("calc_mix_kau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A child and one prospective parent.
        /// </summary>
        public static string calc_rel_ca {
            get {
                return ResourceManager.GetString("calc_rel_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A child and two prospective parents.
        /// </summary>
        public static string calc_rel_caa {
            get {
                return ResourceManager.GetString("calc_rel_caa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The person being checked, the intended parent, and the intended grandparent.
        /// </summary>
        public static string calc_rel_cag {
            get {
                return ResourceManager.GetString("calc_rel_cag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The person being checked, the alleged parent, and the alleged grandparents.
        /// </summary>
        public static string calc_rel_cagg {
            get {
                return ResourceManager.GetString("calc_rel_cagg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The person being checked, the alleged parent, and one alleged sibling.
        /// </summary>
        public static string calc_rel_cas {
            get {
                return ResourceManager.GetString("calc_rel_cas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two children and one prospective parent.
        /// </summary>
        public static string calc_rel_cca {
            get {
                return ResourceManager.GetString("calc_rel_cca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two children and two prospective parents.
        /// </summary>
        public static string calc_rel_ccaa {
            get {
                return ResourceManager.GetString("calc_rel_ccaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Three children and one prospective parent.
        /// </summary>
        public static string calc_rel_ccca {
            get {
                return ResourceManager.GetString("calc_rel_ccca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Three children and two prospective parents.
        /// </summary>
        public static string calc_rel_cccaa {
            get {
                return ResourceManager.GetString("calc_rel_cccaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Three children, one known and one alleged parent.
        /// </summary>
        public static string calc_rel_cccka {
            get {
                return ResourceManager.GetString("calc_rel_cccka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two children, one known and one alleged parent.
        /// </summary>
        public static string calc_rel_ccka {
            get {
                return ResourceManager.GetString("calc_rel_ccka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The person being checked and the alleged grandmother (grandfather).
        /// </summary>
        public static string calc_rel_cg {
            get {
                return ResourceManager.GetString("calc_rel_cg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The person being checked, the alleged grandparents.
        /// </summary>
        public static string calc_rel_cgg {
            get {
                return ResourceManager.GetString("calc_rel_cgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The child, the grandparent, and the verified parent of the child.
        /// </summary>
        public static string calc_rel_cgv {
            get {
                return ResourceManager.GetString("calc_rel_cgv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Child, one known and one presumed parent.
        /// </summary>
        public static string calc_rel_cka {
            get {
                return ResourceManager.GetString("calc_rel_cka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A child, one known parent, a grandparent, and a verifiable parent of the child.
        /// </summary>
        public static string calc_rel_ckgv {
            get {
                return ResourceManager.GetString("calc_rel_ckgv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The person being checked and one alleged brother (sister).
        /// </summary>
        public static string calc_rel_cs {
            get {
                return ResourceManager.GetString("calc_rel_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The person under review and two alleged siblings.
        /// </summary>
        public static string calc_rel_css {
            get {
                return ResourceManager.GetString("calc_rel_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string cap_add {
            get {
                return ResourceManager.GetString("cap_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a genotype.
        /// </summary>
        public static string cap_add_genotype {
            get {
                return ResourceManager.GetString("cap_add_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculations.
        /// </summary>
        public static string cap_calculate {
            get {
                return ResourceManager.GetString("cap_calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string cap_close {
            get {
                return ResourceManager.GetString("cap_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comparison of genotypes.
        /// </summary>
        public static string cap_compare {
            get {
                return ResourceManager.GetString("cap_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Experts/Controls.
        /// </summary>
        public static string cap_contols {
            get {
                return ResourceManager.GetString("cap_contols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string cap_del {
            get {
                return ResourceManager.GetString("cap_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string cap_edit {
            get {
                return ResourceManager.GetString("cap_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit the genotype.
        /// </summary>
        public static string cap_edit_genotype {
            get {
                return ResourceManager.GetString("cap_edit_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as....
        /// </summary>
        public static string cap_file_save_as {
            get {
                return ResourceManager.GetString("cap_file_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From file.
        /// </summary>
        public static string cap_from_file {
            get {
                return ResourceManager.GetString("cap_from_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Genotypes.
        /// </summary>
        public static string cap_genotypes {
            get {
                return ResourceManager.GetString("cap_genotypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of genotypes.
        /// </summary>
        public static string cap_genotypes_list {
            get {
                return ResourceManager.GetString("cap_genotypes_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string cap_help {
            get {
                return ResourceManager.GetString("cap_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Library.
        /// </summary>
        public static string cap_library {
            get {
                return ResourceManager.GetString("cap_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string cap_name {
            get {
                return ResourceManager.GetString("cap_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string cap_off {
            get {
                return ResourceManager.GetString("cap_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On.
        /// </summary>
        public static string cap_on {
            get {
                return ResourceManager.GetString("cap_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string cap_open {
            get {
                return ResourceManager.GetString("cap_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profiles.
        /// </summary>
        public static string cap_profiles {
            get {
                return ResourceManager.GetString("cap_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project.
        /// </summary>
        public static string cap_project {
            get {
                return ResourceManager.GetString("cap_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a project or a file with genotypes.
        /// </summary>
        public static string cap_project_files_select {
            get {
                return ResourceManager.GetString("cap_project_files_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load.
        /// </summary>
        public static string cap_project_load {
            get {
                return ResourceManager.GetString("cap_project_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New project.
        /// </summary>
        public static string cap_project_new {
            get {
                return ResourceManager.GetString("cap_project_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project Selection.
        /// </summary>
        public static string cap_projects_select {
            get {
                return ResourceManager.GetString("cap_projects_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string cap_save {
            get {
                return ResourceManager.GetString("cap_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string cap_select {
            get {
                return ResourceManager.GetString("cap_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string cap_setting {
            get {
                return ResourceManager.GetString("cap_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string cap_theme {
            get {
                return ResourceManager.GetString("cap_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string cap_unselect {
            get {
                return ResourceManager.GetString("cap_unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation of deletion.
        /// </summary>
        public static string conf_delete {
            get {
                return ResourceManager.GetString("conf_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm the deletion of the genotype &apos;{0}&apos;.
        /// </summary>
        public static string conf_delete_genotype {
            get {
                return ResourceManager.GetString("conf_delete_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If not selected, the genotype will be deleted without notifying the user..
        /// </summary>
        public static string desc_confirm_delete_genotype {
            get {
                return ResourceManager.GetString("desc_confirm_delete_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The control/expert &apos;{0}&apos; has not been added to the list.
        /// </summary>
        public static string err_add_expert {
            get {
                return ResourceManager.GetString("err_add_expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The list is empty.
        /// </summary>
        public static string err_empty_list {
            get {
                return ResourceManager.GetString("err_empty_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The value is empty.
        /// </summary>
        public static string err_empty_value {
            get {
                return ResourceManager.GetString("err_empty_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File upload error.
        /// </summary>
        public static string err_load_profile {
            get {
                return ResourceManager.GetString("err_load_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Genotype is not selected.
        /// </summary>
        public static string msg_genotype_not_selected {
            get {
                return ResourceManager.GetString("msg_genotype_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Never show me this again.
        /// </summary>
        public static string msg_no_show {
            get {
                return ResourceManager.GetString("msg_no_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The &apos;{0}&apos; was saved successfully on the way &apos;{1}&apos;.
        /// </summary>
        public static string msg_object_saved {
            get {
                return ResourceManager.GetString("msg_object_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        public static string msg_page_appearance {
            get {
                return ResourceManager.GetString("msg_page_appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculations.
        /// </summary>
        public static string msg_page_calc {
            get {
                return ResourceManager.GetString("msg_page_calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation of genotype deletion.
        /// </summary>
        public static string msg_page_conf_delete_genotype {
            get {
                return ResourceManager.GetString("msg_page_conf_delete_genotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmations.
        /// </summary>
        public static string msg_page_confirmations {
            get {
                return ResourceManager.GetString("msg_page_confirmations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Templates.
        /// </summary>
        public static string msg_page_templates {
            get {
                return ResourceManager.GetString("msg_page_templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploading a file.
        /// </summary>
        public static string msg_uploading_file {
            get {
                return ResourceManager.GetString("msg_uploading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string theme_dark {
            get {
                return ResourceManager.GetString("theme_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select your preferred application theme from the list..
        /// </summary>
        public static string theme_desc {
            get {
                return ResourceManager.GetString("theme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string theme_light {
            get {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System theme.
        /// </summary>
        public static string theme_sys {
            get {
                return ResourceManager.GetString("theme_sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The default template.
        /// </summary>
        public static string tpl_empty_template {
            get {
                return ResourceManager.GetString("tpl_empty_template", resourceCulture);
            }
        }
    }
}
